
export const slides = [{
  image: '/banner-1.jpg',
  heading: 'Discover Your Perfect Fit',
  description: 'Premium quality undergarments for every occasion',
  buttonText: 'Shop Now',
  buttonLink: '#shop-now',
},
{
  image: '/banner-2.jpg',
  heading: 'Elegance Meets Comfort',
  description: 'Available all over Pakistan',
  buttonText: 'Shop Now',
  buttonLink: '#shop-now',
},
{
  image: '/banner-3.jpg',
  heading: 'Easy Returns',
  description: "Don't like it? Return it hassle-free!",
  buttonText: 'Learn More',
  buttonLink: '#return-policy',
},
]

export const policy = [
  {
    icon: 'fa-undo',
    title: 'Easy Returns',
    description: "Don't like what you received? Return it within 7 days!"
  },
  {
    icon: 'fa-truck',
    title: 'Free Pickup',
    description: "We'll pick up your return at no extra cost"
  },
  {
    icon: 'fa-money-bill-wave',
    title: 'Full Refund',
    description: 'Get your money back within 3-5 business days'
  }
]

export const products = [
  {
    name: 'Lace Bralette',
    price: '$29.99',
    image: '/banner-1.jpg',
  },
  {
    name: 'Silk Camisole',
    price: '$39.99',
    image: '/banner-2.jpg',
  },
  {
    name: 'Cotton Briefs',
    price: '$19.99',
    image: '/banner-3.jpg',
  },
  {
    name: 'Sleep Set',
    price: '$49.99',
    image: '/banner-1.jpg',
  }
]

export const category = [{
  text: 'Bras',
  image: '/banner-1.jpg',
},
{
  text: 'Panties',
  image: '/banner-2.jpg',
},
{
  text: 'Lingerie',
  image: '/banner-3.jpg',
},
{
  text: 'Sleepwear',
  image: '/banner-1.jpg',
}]

export const cartItems = [
  {
    id: 1,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1700,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 2,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1700,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 3,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1700,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 4,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1700,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 5,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1700,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 6,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 20000,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 7,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1900,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 8,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1500,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 9,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1700,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
  {
    id: 10,
    name: 'Q-EN Bamboo Camisole Black 705',
    price: 1700,
    image: '/banner-1.jpg',
    quantity: 1,
    stock: true,
    delivery: '1-3 Days',
    area: 'Nationwide',
    origin: 'Türkiye',
    shippedBy: 'Naheed',
    options: ['S', 'M', 'L', 'XL'],
    selectedOption: '',
  },
];
